### ISSUE TITLE
About snow effect

### ISSUE THREAD

**Issue by gisonjourney** [nagix/mapbox-gl-rain-layer#20]
Hello, this is a very nice demo, but snow function can not work well, what's wrong with snow?

**Comment by nagix** [comment]
Hi, could you elaborate the issue a little more? I can see snow falling in the mountains of Argentina and New Zealand.

**Comment by gisonjourney** [comment]
> Hi, could you elaborate the issue a little more? I can see snow falling in the mountains of Argentina and New Zealand.

I've solved this problem, but i have another question?If i want use this offline, what should i do?

**Comment by nagix** [comment]
This plugin uses live information and cannot be used offline.
